CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Ime] NVARCHAR(50) NOT NULL,
	[Imeoca] NVARCHAR(50) NOT NULL,
	[Adresa] NVARCHAR(50) NOT NULL,
	[Pol] NVARCHAR(50) NOT NULL
)
